"""AppSumo Licensing API v2 integration.

Two public endpoints + one admin endpoint, all registered on the shared
`api` sub-app from server.py (mounted at /api):

  - POST /api/appsumo-webhook?token=...   — AppSumo license event receiver.
    Handles purchase / activate / upgrade / downgrade / deactivate / migrate
    and the Partner Portal's test pings. Token-gated (same pattern as the
    Pinball webhook) with optional HMAC SHA256 verification on top.
  - POST /api/appsumo/redeem              — OAuth code exchange. Called by the
    /redeem page after AppSumo redirects the buyer with ?code=. Exchanges the
    code for the buyer's license_key, links it to their email, and grants
    entitlements in db.buyers so the normal email sign-in works.
  - GET  /api/admin/appsumo/licenses      — admin-gated license search, so
    support can look up any license_key (AppSumo requires partners to keep
    license keys searchable — AppSumo itself never stores customer emails).

Storage:
  - db.appsumo_licenses — one doc per license_key (the durable record).
  - db.activity         — every webhook + redemption logged via log_activity,
    same trail the Admin → Activity UI already reads.

Entitlement model: an AppSumo tier maps to a set of the existing
entitlements (base/shorts/studio) via APPSUMO_TIER_MAP. When a license is
redeemed we grant the tier's entitlements and remember exactly which ones
were NEW for that buyer on the license doc, so a later deactivate (refund)
removes only what AppSumo granted — a Pinball customer who also bought on
AppSumo keeps their original purchases.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import re
from datetime import datetime, timezone
from typing import Any, Optional

import httpx
from fastapi import HTTPException, Query, Request
from pydantic import BaseModel

logger = logging.getLogger("f48.appsumo")

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Shared secret in the webhook URL's ?token= query param — the `as_...` value
# baked into the Webhook URL saved in the AppSumo Partner Portal. Single gate,
# same pattern as PINBALL_WEBHOOK_TOKEN. Empty value = endpoint disabled.
APPSUMO_WEBHOOK_TOKEN = os.environ.get("APPSUMO_WEBHOOK_TOKEN", "").strip()

# The Partner Portal API key ("private_key" on the Connect to the Partner API
# page). When set, every webhook's X-Appsumo-Signature header is verified as
# HMAC SHA256 of (X-Appsumo-Timestamp + raw body). Optional — leave unset
# until the final key is issued on submission and the token gate still holds.
APPSUMO_API_KEY = os.environ.get("APPSUMO_API_KEY", "").strip()

# OAuth credentials — auto-generated by AppSumo after both URLs validate in
# the Partner Portal. Required only by /appsumo/redeem.
APPSUMO_CLIENT_ID = os.environ.get("APPSUMO_CLIENT_ID", "").strip()
APPSUMO_CLIENT_SECRET = os.environ.get("APPSUMO_CLIENT_SECRET", "").strip()
# Must byte-for-byte match the OAuth redirect URL saved in the Partner Portal.
APPSUMO_REDIRECT_URI = os.environ.get(
    "APPSUMO_REDIRECT_URI", "https://faceless48.c3global.co/redeem"
).strip()

APPSUMO_TOKEN_URL = "https://appsumo.com/openid/token/"
APPSUMO_LICENSE_URL = "https://appsumo.com/openid/license_key/"

# AppSumo tier number → entitlements granted. JSON env override so new tiers
# don't need a code change (same convention as PINBALL_PRODUCT_MAP).
DEFAULT_APPSUMO_TIER_MAP = {
    "1": ["base"],
    "2": ["base", "shorts"],
    "3": ["base", "shorts", "studio"],
}
try:
    _env_map = os.environ.get("APPSUMO_TIER_MAP", "").strip()
    APPSUMO_TIER_MAP = json.loads(_env_map) if _env_map else DEFAULT_APPSUMO_TIER_MAP
except json.JSONDecodeError:
    logger.warning("APPSUMO_TIER_MAP env var is not valid JSON, falling back to defaults")
    APPSUMO_TIER_MAP = DEFAULT_APPSUMO_TIER_MAP

STUDIO_LIFETIME_PERIOD_END = "2099-01-01T00:00:00Z"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _tier_entitlements(tier: Any) -> list[str]:
    """Entitlements for an AppSumo tier. Unknown tiers fall back to tier 1
    (better to under-grant a brand-new tier than to drop the webhook)."""
    ents = APPSUMO_TIER_MAP.get(str(tier or 1))
    if ents is None:
        logger.warning(f"[appsumo] unknown tier {tier!r}; falling back to tier 1")
        ents = APPSUMO_TIER_MAP.get("1", ["base"])
    return sorted(set(ents))


def _verify_signature(raw_body: bytes, timestamp: str, signature: str) -> bool:
    """HMAC SHA256 of (timestamp + raw body) keyed with the Partner API key,
    hex-encoded, compared against X-Appsumo-Signature in constant time."""
    expected = hmac.new(
        APPSUMO_API_KEY.encode("utf-8"),
        timestamp.encode("utf-8") + raw_body,
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(expected.lower(), (signature or "").strip().lower())


class RedeemPayload(BaseModel):
    code: str
    email: str


def register_appsumo_routes(*, api, db, current_user, log_activity) -> None:
    """Attach the AppSumo webhook + OAuth redemption routes to the shared
    `api` FastAPI sub-app. Mirrors register_admin_routes' wiring style."""
    from fastapi import Depends  # noqa: PLC0415 — keep module surface tiny

    # ------------------------------------------------------------------
    # Shared grant / revoke helpers
    # ------------------------------------------------------------------
    async def _grant_for_license(email: str, lic: dict) -> list[str]:
        """Grant the license's tier entitlements to `email` in db.buyers.
        Records which entitlements were newly added by THIS license on the
        license doc so a refund only claws back AppSumo's own grants.
        Returns the buyer's full entitlement list after the merge."""
        ents = _tier_entitlements(lic.get("tier"))
        buyer = await db.buyers.find_one({"email": email})
        prev = set((buyer.get("entitlements") if buyer else []) or [])
        newly = sorted(set(ents) - prev)
        merged = sorted(prev | set(ents))

        set_doc: dict[str, Any] = {
            "email": email,
            "entitlements": merged,
            "updatedAt": _now_iso(),
            "source": "appsumo" if not buyer else (buyer.get("source") or "appsumo"),
        }
        if "studio" in ents:
            set_doc["studio_status"] = "active"
            set_doc["studio_lifetime"] = True
            set_doc["studio_current_period_end"] = STUDIO_LIFETIME_PERIOD_END
        if newly:
            set_doc["pending_welcome"] = True
            set_doc["pending_welcome_ents"] = newly
        update: dict[str, Any] = {
            "$set": set_doc,
            "$addToSet": {"appsumo_license_keys": lic["license_key"]},
        }
        if not buyer:
            update["$setOnInsert"] = {"addedAt": _now_iso()}
        await db.buyers.update_one({"email": email}, update, upsert=True)

        await db.appsumo_licenses.update_one(
            {"license_key": lic["license_key"]},
            {"$set": {"email": email, "granted_entitlements": newly, "updatedAt": _now_iso()}},
        )
        return merged

    async def _revoke_for_license(lic: dict) -> list[str]:
        """Claw back what THIS license granted, but keep any entitlement still
        covered by another active AppSumo license on the same email (upgrade
        flows: the new key's grant must survive the old key's deactivate)."""
        email = lic.get("email")
        removable = set(lic.get("granted_entitlements") or [])
        if not email or not removable:
            return []
        keep: set[str] = set()
        async for other in db.appsumo_licenses.find(
            {"email": email, "status": "active", "license_key": {"$ne": lic["license_key"]}}
        ):
            keep |= set(_tier_entitlements(other.get("tier")))
        to_remove = sorted(removable - keep)
        if not to_remove:
            return []
        buyer = await db.buyers.find_one({"email": email})
        if not buyer:
            return []
        remaining = sorted(set(buyer.get("entitlements") or []) - set(to_remove))
        unset_doc: dict[str, Any] = {}
        if "studio" in to_remove:
            unset_doc = {"studio_status": "", "studio_lifetime": "", "studio_current_period_end": ""}
        update: dict[str, Any] = {
            "$set": {"entitlements": remaining, "updatedAt": _now_iso()},
            "$pull": {"appsumo_license_keys": lic["license_key"]},
        }
        if unset_doc:
            update["$unset"] = unset_doc
        await db.buyers.update_one({"email": email}, update)
        return to_remove

    # ------------------------------------------------------------------
    # Webhook receiver
    # ------------------------------------------------------------------
    @api.post("/appsumo-webhook")
    async def appsumo_webhook(request: Request, token: str = Query(...)):
        # 1) Token gate — empty configured value means "endpoint disabled".
        if not APPSUMO_WEBHOOK_TOKEN or not hmac.compare_digest(token, APPSUMO_WEBHOOK_TOKEN):
            await log_activity(
                "webhook_failed",
                "",
                {"reason": "invalid token", "source": "appsumo"},
            )
            raise HTTPException(status_code=401, detail="Invalid token")

        raw = await request.body()

        # 2) Optional HMAC verification (enabled once APPSUMO_API_KEY is set).
        if APPSUMO_API_KEY:
            ts = request.headers.get("X-Appsumo-Timestamp", "")
            sig = request.headers.get("X-Appsumo-Signature", "")
            if not _verify_signature(raw, ts, sig):
                await log_activity(
                    "webhook_failed",
                    "",
                    {"reason": "invalid HMAC signature", "source": "appsumo"},
                )
                raise HTTPException(status_code=401, detail="Invalid signature")

        # 3) Parse — AppSumo ships JSON or form-encoded.
        body: dict = {}
        try:
            body = json.loads(raw.decode("utf-8"))
        except Exception:
            try:
                form = await request.form()
                body = dict(form)
            except Exception:
                body = {}
        if not isinstance(body, dict) or not body.get("event") or not body.get("license_key"):
            await log_activity(
                "webhook_failed",
                "",
                {"reason": "malformed payload", "source": "appsumo",
                 "payload": raw.decode("utf-8", "replace")[:1000]},
            )
            raise HTTPException(status_code=400, detail="Malformed payload")

        event = str(body["event"]).strip().lower()
        license_key = str(body["license_key"]).strip()
        is_test = bool(body.get("test"))

        # 4) Partner Portal validation pings — acknowledge, change nothing.
        if is_test:
            await log_activity(
                "webhook", "",
                {"status": "test", "event": event, "license_key": license_key, "source": "appsumo"},
            )
            return {"event": event, "success": True}

        # 5) Upsert the license doc. AppSumo is the source of truth for keys;
        #    we keep a durable, support-searchable mirror.
        base_fields = {
            "license_key": license_key,
            "tier": body.get("tier"),
            "last_event": event,
            "last_event_timestamp": body.get("event_timestamp"),
            "appsumo_created_at": body.get("created_at"),
            "partner_plan_name": body.get("partner_plan_name"),
            "unit_quantity": body.get("unit_quantity"),
            "parent_license_key": body.get("parent_license_key"),
            "extra": body.get("extra"),
            "updatedAt": _now_iso(),
        }
        # Drop Nones so a sparse payload (e.g. deactivate has no tier) never
        # erases fields learned from earlier events.
        base_fields = {k: v for k, v in base_fields.items() if v is not None}

        detail: dict[str, Any] = {
            "status": "ok", "event": event, "license_key": license_key, "source": "appsumo",
        }

        if event == "purchase":
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": {**base_fields, "status": "purchased"},
                 "$setOnInsert": {"addedAt": _now_iso()}},
                upsert=True,
            )

        elif event == "activate":
            # license_status arrives "inactive" by design — AppSumo flips it
            # to active only after we return 200.
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": {**base_fields, "status": "active", "activated_at": _now_iso()},
                 "$setOnInsert": {"addedAt": _now_iso()}},
                upsert=True,
            )
            lic = await db.appsumo_licenses.find_one({"license_key": license_key})
            if lic and lic.get("email"):
                ents = await _grant_for_license(lic["email"], lic)
                detail["email"] = lic["email"]
                detail["entitlements"] = ents

        elif event in ("upgrade", "downgrade"):
            # New key is always issued; the old key gets its own simultaneous
            # deactivate event. Carry the email link over via prev_license_key.
            prev_key = str(body.get("prev_license_key") or "").strip()
            email: Optional[str] = None
            if prev_key:
                old = await db.appsumo_licenses.find_one({"license_key": prev_key})
                if old:
                    email = old.get("email")
            update = {"$set": {**base_fields, "status": "active",
                               "prev_license_key": prev_key or None},
                      "$setOnInsert": {"addedAt": _now_iso()}}
            if email:
                update["$set"]["email"] = email
            update["$set"] = {k: v for k, v in update["$set"].items() if v is not None}
            await db.appsumo_licenses.update_one(
                {"license_key": license_key}, update, upsert=True
            )
            if email:
                lic = await db.appsumo_licenses.find_one({"license_key": license_key})
                ents = await _grant_for_license(email, lic)
                detail["email"] = email
                detail["entitlements"] = ents

        elif event == "deactivate":
            # license_status arrives "active" by design — AppSumo deactivates
            # after we return 200. Refunds/cancellations land here.
            lic = await db.appsumo_licenses.find_one({"license_key": license_key})
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": {**base_fields, "status": "deactivated", "deactivated_at": _now_iso()},
                 "$setOnInsert": {"addedAt": _now_iso()}},
                upsert=True,
            )
            if lic:
                removed = await _revoke_for_license(lic)
                if removed:
                    detail["email"] = lic.get("email")
                    detail["revoked"] = removed

        elif event == "migrate":
            # Add-on follows its parent deal's upgrade/downgrade: the add-on's
            # own key is stable, only parent_license_key changes.
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": base_fields, "$setOnInsert": {"addedAt": _now_iso(), "status": "active"}},
                upsert=True,
            )

        else:
            # Unknown event type — record it and still ACK so AppSumo doesn't
            # retry forever; the activity log surfaces it for investigation.
            detail["status"] = "unknown_event"
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": base_fields, "$setOnInsert": {"addedAt": _now_iso()}},
                upsert=True,
            )

        await log_activity("webhook", detail.get("email") or "", detail)
        return {"event": event, "success": True}

    # ------------------------------------------------------------------
    # OAuth redemption — called by the /redeem page with ?code= from AppSumo
    # ------------------------------------------------------------------
    @api.post("/appsumo/redeem")
    async def appsumo_redeem(payload: RedeemPayload):
        email = payload.email.strip().lower()
        code = payload.code.strip()
        if not EMAIL_RE.match(email):
            raise HTTPException(status_code=400, detail="Enter a valid email address.")
        if not code:
            raise HTTPException(status_code=400, detail="Missing AppSumo code. Please restart activation from AppSumo.")
        if not APPSUMO_CLIENT_ID or not APPSUMO_CLIENT_SECRET:
            raise HTTPException(
                status_code=503,
                detail="AppSumo activation isn't configured yet. Please contact support@c3global.co.",
            )

        # Exchange the single-use code for an access token, then the token
        # for the buyer's license_key.
        async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, connect=10.0)) as client:
            tr = await client.post(
                APPSUMO_TOKEN_URL,
                data={
                    "client_id": APPSUMO_CLIENT_ID,
                    "client_secret": APPSUMO_CLIENT_SECRET,
                    "redirect_uri": APPSUMO_REDIRECT_URI,
                    "code": code,
                    "grant_type": "authorization_code",
                },
            )
            if tr.status_code != 200:
                logger.warning(f"[appsumo] token exchange failed {tr.status_code}: {tr.text[:300]}")
                await log_activity(
                    "appsumo_redeem_failed", email,
                    {"reason": "token exchange failed", "status": tr.status_code},
                )
                raise HTTPException(
                    status_code=400,
                    detail="AppSumo code expired or already used. Please restart activation from your AppSumo account.",
                )
            access_token = (tr.json() or {}).get("access_token")
            if not access_token:
                raise HTTPException(status_code=502, detail="AppSumo did not return an access token. Please try again.")

            lr = await client.get(APPSUMO_LICENSE_URL, params={"access_token": access_token})
            if lr.status_code != 200:
                logger.warning(f"[appsumo] license fetch failed {lr.status_code}: {lr.text[:300]}")
                raise HTTPException(status_code=502, detail="Could not fetch your AppSumo license. Please try again.")
            lic_resp = lr.json() or {}

        license_key = (lic_resp.get("license_key") or "").strip()
        license_status = (lic_resp.get("status") or "").strip().lower()
        if not license_key:
            raise HTTPException(status_code=502, detail="AppSumo did not return a license key. Please try again.")
        if license_status == "deactivated":
            raise HTTPException(
                status_code=410,
                detail="This AppSumo license is no longer active. Contact AppSumo support if you believe this is an error.",
            )

        lic = await db.appsumo_licenses.find_one({"license_key": license_key})
        if lic and lic.get("email") and lic["email"] != email:
            await log_activity(
                "appsumo_redeem_failed", email,
                {"reason": "license already linked to another email", "license_key": license_key},
            )
            raise HTTPException(
                status_code=409,
                detail="This AppSumo license is already linked to a different email. Sign in with that email or contact support@c3global.co.",
            )
        if not lic:
            # Webhook may not have landed yet (or arrived out of order) —
            # create the record now; the webhook upsert will enrich it later.
            await db.appsumo_licenses.update_one(
                {"license_key": license_key},
                {"$set": {"license_key": license_key, "status": "active",
                          "last_event": "redeem", "updatedAt": _now_iso()},
                 "$setOnInsert": {"addedAt": _now_iso()}},
                upsert=True,
            )
            lic = await db.appsumo_licenses.find_one({"license_key": license_key})

        ents = await _grant_for_license(email, lic)

        # Link any add-ons of this deal to the same email so future add-on
        # events resolve to a buyer.
        await db.appsumo_licenses.update_many(
            {"parent_license_key": license_key},
            {"$set": {"email": email, "updatedAt": _now_iso()}},
        )

        await log_activity(
            "appsumo_redeem", email,
            {"status": "ok", "license_key": license_key, "entitlements": ents},
        )
        return {"ok": True, "email": email, "entitlements": ents}

    # ------------------------------------------------------------------
    # Admin — support-searchable license lookup (AppSumo partner requirement)
    # ------------------------------------------------------------------
    @api.get("/admin/appsumo/licenses")
    async def admin_appsumo_licenses(
        q: str = Query(default="", description="license_key or email substring"),
        page: int = Query(default=1, ge=1),
        limit: int = Query(default=50, ge=1, le=200),
        user=Depends(current_user),
    ):
        if not user.is_admin:
            raise HTTPException(status_code=403, detail="Admin only")
        filt: dict[str, Any] = {}
        if q.strip():
            rx = {"$regex": re.escape(q.strip()), "$options": "i"}
            filt = {"$or": [{"license_key": rx}, {"email": rx}]}
        total = await db.appsumo_licenses.count_documents(filt)
        cursor = (
            db.appsumo_licenses.find(filt, {"_id": 0})
            .sort("updatedAt", -1)
            .skip((page - 1) * limit)
            .limit(limit)
        )
        items = [doc async for doc in cursor]
        return {"items": items, "total": total, "page": page, "limit": limit}
